trainings:
  - name: pa_progressive_summit_field_feb_2016
    date: Feb. 19, 2016
    location: Harrisburg, PA
    type: Field Training at the PA Progressive Summit
  - name: pa_progressive_summit_finance_feb_2016
    date: Feb. 19, 2016
    location: Harrisburg, PA
    type: Finance Training at the PA Progressive Summit
markdown: kramdown
