trainings:
  - name: pa_may_fin
    date: May 24-25, 2014
    location: Philadelphia, PA
    type: Finance Training
  - name: me_may_fin
    date: May 30, 2014
    location: Maine
    type: Finance Training
  - name: ca_june_field
    date: June 7-8, 2014
    location: Los Angeles, CA
    type: Field Training
  - name: sd_june_field
    date: June 28-29, 2014
    location: South Dakota
    type: Field Training
  - name: me_july_field
    date: July 12-13, 2014
    location: Maine
    type: Field Training
markdown: kramdown
