trainings:
  - name: sd_june_field
    date: June 28-29, 2014
    location: South Dakota
    type: Field Training
  - name: me_july_field
    date: July 12-13, 2014
    location: Portland, Maine
    type: Field Training
markdown: kramdown
